/*
 * generated by Xtext 2.20.0
 */
package it.imt.erode.crn.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class ChemicalReactionNetworkOutlineTreeProvider extends DefaultOutlineTreeProvider {

	@Override
	  public IOutlineNode createRoot(final IXtextDocument document) {
	    IOutlineNode documentNode = super.createRoot(document);
	    int _size = documentNode.getChildren().size();
	    boolean _greaterThan = (_size > 0);
	    if (_greaterThan) {
	      IOutlineNode modelDef = documentNode.getChildren().get(0);
	      return modelDef;
	    } else {
	      return documentNode;
	    }
	  }
}
