/*
 * generated by Xtext 2.24.0
 */
package it.imt.erode.crn.ui.tests;

import com.google.inject.Injector;
import it.imt.erode.crn.ui.internal.CrnActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ChemicalReactionNetworkUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CrnActivator.getInstance().getInjector("it.imt.erode.crn.ChemicalReactionNetwork");
	}

}
