/*
 * generated by Xtext 2.20.0
 */
package it.imt.erode.crn.ide;


/**
 * Use this class to register ide components.
 */
public class ChemicalReactionNetworkIdeModule extends AbstractChemicalReactionNetworkIdeModule {
}
