/*
 * generated by Xtext 2.20.0
 */
package it.imt.erode.crn.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.imt.erode.crn.ChemicalReactionNetworkRuntimeModule;
import it.imt.erode.crn.ChemicalReactionNetworkStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ChemicalReactionNetworkIdeSetup extends ChemicalReactionNetworkStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ChemicalReactionNetworkRuntimeModule(), new ChemicalReactionNetworkIdeModule()));
	}
	
}
