/*
 * generated by Xtext 2.20.0
 */
package it.imt.erode.crn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ChemicalReactionNetworkUiModule extends AbstractChemicalReactionNetworkUiModule {

	public ChemicalReactionNetworkUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
